"""
LLM Narrative Generation Service for SIH26106 Forensics.
Calls Ollama via host.docker.internal with deterministic template fallback.
"""

import os
import json
import asyncio
import logging
from typing import Dict, Any, Optional
from datetime import datetime

import httpx

logger = logging.getLogger(__name__)

# Configuration
OLLAMA_HOST = os.environ.get("OLLAMA_HOST", "http://host.docker.internal:11434")
OLLAMA_MODEL = os.environ.get("OLLAMA_MODEL", "llama3.2:3b")
OLLAMA_TIMEOUT = float(os.environ.get("OLLAMA_TIMEOUT", "60.0"))
USE_MOCK = os.environ.get("NEXT_PUBLIC_USE_MOCK", "false").lower() == "true"

# Deterministic template for fallback
NARRATIVE_TEMPLATE = """
**Forensic Email Analysis Narrative**

**Case ID:** {case_id}
**Analysis Timestamp:** {timestamp}
**Parser Version:** {parser_version}

**Executive Summary**
{summary}

**Technical Findings**

*Authentication Results:*
{auth_results}

*Routing Analysis:*
{routing_analysis}

*Content Analysis:*
{content_analysis}

*IOC Summary:*
{ioc_summary}

**Risk Assessment**
Overall Risk Score: {risk_score}/100
Classification: {classification}

**Recommendations**
{recommendations}

---
*Generated by SIH26106 Forensics Platform*
*LLM Model: {model} ({generation_method})*
"""


async def generate_narrative(
    analysis_data: Dict[str, Any],
    case_id: str,
    parser_version: str = "1.0.0"
) -> Dict[str, Any]:
    """
    Generate a human-readable narrative from analysis JSON.
    
    Args:
        analysis_data: Full analysis JSON from forensic analyzer
        case_id: Case identifier
        parser_version: Version of the parser used
        
    Returns:
        Dictionary with narrative text and metadata
    """
    timestamp = datetime.utcnow().isoformat() + "Z"
    
    if USE_MOCK:
        logger.info("Mock mode enabled, using template fallback")
        return _generate_template_narrative(
            analysis_data, case_id, parser_version, timestamp, "mock"
        )
    
    # Try Ollama first
    try:
        narrative = await _call_ollama(analysis_data, case_id, parser_version, timestamp)
        if narrative:
            return {
                "narrative": narrative,
                "generation_method": "ollama",
                "model": OLLAMA_MODEL,
                "timestamp": timestamp
            }
    except Exception as e:
        logger.warning(f"Ollama call failed, falling back to template: {e}")
    
    # Fallback to deterministic template
    return _generate_template_narrative(
        analysis_data, case_id, parser_version, timestamp, "template_fallback"
    )


async def _call_ollama(
    analysis_data: Dict[str, Any],
    case_id: str,
    parser_version: str,
    timestamp: str
) -> Optional[str]:
    """Call Ollama API to generate narrative."""
    
    prompt = _build_prompt(analysis_data, case_id, parser_version, timestamp)
    
    async with httpx.AsyncClient(timeout=OLLAMA_TIMEOUT) as client:
        response = await client.post(
            f"{OLLAMA_HOST}/api/generate",
            json={
                "model": OLLAMA_MODEL,
                "prompt": prompt,
                "stream": False,
                "options": {
                    "temperature": 0.1,
                    "top_p": 0.9,
                    "num_predict": 2048,
                }
            }
        )
        response.raise_for_status()
        result = response.json()
        return result.get("response", "").strip()


def _build_prompt(
    analysis_data: Dict[str, Any],
    case_id: str,
    parser_version: str,
    timestamp: str
) -> str:
    """Build the prompt for Ollama."""
    
    # Extract key fields for prompt
    auth = analysis_data.get("authentication", {})
    routing = analysis_data.get("routing", {})
    content = analysis_data.get("content", {})
    iocs = analysis_data.get("iocs", {})
    ml = analysis_data.get("ml_analysis", {})
    
    prompt = f"""You are a digital forensics expert writing an executive summary for an email forensic analysis report.

CASE ID: {case_id}
TIMESTAMP: {timestamp}
PARSER VERSION: {parser_version}

ANALYSIS DATA:
{json.dumps(analysis_data, indent=2)}

Write a professional forensic narrative report with these sections:
1. Executive Summary (2-3 sentences)
2. Authentication Results (SPF/DKIM/DMARC details)
3. Routing Analysis (hop count, delays, anomalies)
4. Content Analysis (suspicious patterns, attachments)
5. IOC Summary (counts by type)
6. Risk Assessment (score and classification)
7. Recommendations (3-5 actionable items)

Keep it concise, technical but readable. Use markdown formatting.
"""
    return prompt


def _generate_template_narrative(
    analysis_data: Dict[str, Any],
    case_id: str,
    parser_version: str,
    timestamp: str,
    generation_method: str
) -> Dict[str, Any]:
    """Generate narrative using deterministic template."""
    
    # Extract data with defaults
    auth = analysis_data.get("authentication", {})
    routing = analysis_data.get("routing", {})
    content = analysis_data.get("content", {})
    iocs = analysis_data.get("iocs", {})
    ml = analysis_data.get("ml_analysis", {})
    risk = analysis_data.get("risk_assessment", {})
    
    # Build sections
    summary = _build_summary(auth, routing, content, risk)
    auth_results = _build_auth_section(auth)
    routing_analysis = _build_routing_section(routing)
    content_analysis = _build_content_section(content)
    ioc_summary = _build_ioc_section(iocs)
    risk_score = risk.get("score", 0)
    classification = risk.get("classification", "UNKNOWN")
    recommendations = _build_recommendations(auth, routing, content, iocs, risk)
    
    narrative = NARRATIVE_TEMPLATE.format(
        case_id=case_id,
        timestamp=timestamp,
        parser_version=parser_version,
        summary=summary,
        auth_results=auth_results,
        routing_analysis=routing_analysis,
        content_analysis=content_analysis,
        ioc_summary=ioc_summary,
        risk_score=risk_score,
        classification=classification,
        recommendations=recommendations,
        model=OLLAMA_MODEL,
        generation_method=generation_method
    )
    
    return {
        "narrative": narrative.strip(),
        "generation_method": generation_method,
        "model": OLLAMA_MODEL,
        "timestamp": timestamp
    }


def _build_summary(auth: Dict, routing: Dict, content: Dict, risk: Dict) -> str:
    """Build executive summary."""
    auth_status = []
    if auth.get("spf") == "pass":
        auth_status.append("SPF passed")
    elif auth.get("spf") == "fail":
        auth_status.append("SPF failed")
    
    if auth.get("dkim") == "pass":
        auth_status.append("DKIM passed")
    elif auth.get("dkim") == "fail":
        auth_status.append("DKIM failed")
    
    if auth.get("dmarc") == "pass":
        auth_status.append("DMARC passed")
    elif auth.get("dmarc") == "fail":
        auth_status.append("DMARC failed")
    
    hop_count = routing.get("hop_count", 0)
    risk_score = risk.get("score", 0)
    classification = risk.get("classification", "UNKNOWN")
    
    return (
        f"This email forensic analysis examined authentication, routing, and content characteristics. "
        f"Authentication results: {', '.join(auth_status) if auth_status else 'No authentication data'}. "
        f"Routing path contained {hop_count} hops. "
        f"Overall risk classification: {classification} (score: {risk_score}/100)."
    )


def _build_auth_section(auth: Dict) -> str:
    """Build authentication results section."""
    if not auth:
        return "No authentication data available."
    
    lines = []
    for check in ["spf", "dkim", "dmarc", "arc"]:
        value = auth.get(check, "unknown")
        lines.append(f"- **{check.upper()}:** {value}")
    
    # Add details if present
    for check in ["spf", "dkim", "dmarc"]:
        detail_key = f"{check}_detail"
        if detail_key in auth:
            lines.append(f"  - Details: {auth[detail_key]}")
    
    return "\n".join(lines)


def _build_routing_section(routing: Dict) -> str:
    """Build routing analysis section."""
    if not routing:
        return "No routing data available."
    
    lines = []
    lines.append(f"- **Hop Count:** {routing.get('hop_count', 'unknown')}")
    lines.append(f"- **Total Delay:** {routing.get('total_delay_ms', 'unknown')} ms")
    
    if routing.get("anomalies"):
        lines.append("- **Anomalies Detected:**")
        for anomaly in routing["anomalies"]:
            lines.append(f"  - {anomaly}")
    else:
        lines.append("- **Anomalies:** None detected")
    
    if routing.get("suspicious_relays"):
        lines.append("- **Suspicious Relays:**")
        for relay in routing["suspicious_relays"]:
            lines.append(f"  - {relay}")
    
    return "\n".join(lines)


def _build_content_section(content: Dict) -> str:
    """Build content analysis section."""
    if not content:
        return "No content analysis data available."
    
    lines = []
    
    if "suspicious_patterns" in content:
        patterns = content["suspicious_patterns"]
        if patterns:
            lines.append("- **Suspicious Patterns:**")
            for p in patterns:
                lines.append(f"  - {p}")
        else:
            lines.append("- **Suspicious Patterns:** None detected")
    
    if "attachments" in content:
        attachments = content["attachments"]
        if attachments:
            lines.append(f"- **Attachments ({len(attachments)}):**")
            for att in attachments:
                lines.append(f"  - {att.get('filename', 'unknown')} ({att.get('type', 'unknown')}, {att.get('size', 0)} bytes)")
        else:
            lines.append("- **Attachments:** None")
    
    if "urls" in content:
        urls = content["urls"]
        if urls:
            lines.append(f"- **URLs Found ({len(urls)}):**")
            for url in urls[:5]:  # Limit to 5
                lines.append(f"  - {url}")
            if len(urls) > 5:
                lines.append(f"  - ... and {len(urls) - 5} more")
    
    return "\n".join(lines) if lines else "No significant content findings."


def _build_ioc_section(iocs: Dict) -> str:
    """Build IOC summary section."""
    if not iocs:
        return "No indicators of compromise extracted."
    
    lines = []
    total = 0
    
    for ioc_type in ["ips", "domains", "urls", "hashes", "emails", "cves"]:
        items = iocs.get(ioc_type, [])
        count = len(items) if isinstance(items, list) else 0
        total += count
        if count > 0:
            lines.append(f"- **{ioc_type.upper()}:** {count}")
            for item in items[:3]:  # Show first 3
                lines.append(f"  - {item}")
            if count > 3:
                lines.append(f"  - ... and {count - 3} more")
    
    if total == 0:
        return "No indicators of compromise extracted."
    
    lines.insert(0, f"**Total IOCs:** {total}")
    return "\n".join(lines)


def _build_recommendations(
    auth: Dict, routing: Dict, content: Dict, iocs: Dict, risk: Dict
) -> str:
    """Build recommendations section."""
    recommendations = []
    
    # Auth-based recommendations
    if auth.get("spf") == "fail" or auth.get("dkim") == "fail" or auth.get("dmarc") == "fail":
        recommendations.append(
            "Investigate authentication failures - potential spoofing or misconfiguration."
        )
    
    # Routing-based
    if routing.get("anomalies"):
        recommendations.append(
            "Review routing anomalies for potential traffic interception or manipulation."
        )
    
    if routing.get("suspicious_relays"):
        recommendations.append(
            "Investigate suspicious relay hosts in the delivery path."
        )
    
    # Content-based
    if content.get("suspicious_patterns"):
        recommendations.append(
            "Analyze suspicious content patterns for phishing or malware indicators."
        )
    
    if content.get("attachments"):
        recommendations.append(
            "Sandbox and analyze all attachments in isolated environment."
        )
    
    # IOC-based
    ioc_total = sum(len(v) for v in iocs.values() if isinstance(v, list))
    if ioc_total > 0:
        recommendations.append(
            f"Cross-reference {ioc_total} extracted IOCs against threat intelligence feeds."
        )
    
    # Risk-based
    risk_score = risk.get("score", 0)
    if risk_score >= 70:
        recommendations.append(
            "HIGH PRIORITY: Escalate to incident response team immediately."
        )
    elif risk_score >= 40:
        recommendations.append(
            "Medium priority: Schedule detailed forensic review within 24 hours."
        )
    
    # Default recommendations if none generated
    if not recommendations:
        recommendations = [
            "No immediate action required based on current analysis.",
            "Archive case for future reference and correlation.",
            "Monitor for related events in SIEM."
        ]
    
    return "\n".join(f"{i+1}. {r}" for i, r in enumerate(recommendations))


# Synchronous wrapper for backwards compatibility
def generate_narrative_sync(
    analysis_data: Dict[str, Any],
    case_id: str,
    parser_version: str = "1.0.0"
) -> Dict[str, Any]:
    """Synchronous wrapper for generate_narrative."""
    return asyncio.run(generate_narrative(analysis_data, case_id, parser_version))


# Health check for Ollama connectivity
async def check_ollama_health() -> Dict[str, Any]:
    """Check if Ollama is reachable and has the required model."""
    try:
        async with httpx.AsyncClient(timeout=10.0) as client:
            response = await client.get(f"{OLLAMA_HOST}/api/tags")
            response.raise_for_status()
            data = response.json()
            models = [m.get("name", "") for m in data.get("models", [])]
            has_model = OLLAMA_MODEL in models
            return {
                "status": "healthy" if has_model else "model_missing",
                "models": models,
                "required_model": OLLAMA_MODEL,
                "has_required_model": has_model
            }
    except Exception as e:
        return {
            "status": "unreachable",
            "error": str(e),
            "required_model": OLLAMA_MODEL
        }


def check_ollama_health_sync() -> Dict[str, Any]:
    """Synchronous health check."""
    return asyncio.run(check_ollama_health())
